/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enriched flows
         * @description Returns a list of network flows with threat intelligence and analysis.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of flows to return */
                    limit?: number;
                    /** @description Filter flows by job ID */
                    job_id?: string;
                    /** @description Filter by source IP address */
                    src_ip?: string;
                    /** @description Filter by destination IP address */
                    dst_ip?: string;
                    /** @description Filter by protocol (TCP/UDP) */
                    protocol?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrichedFlow"][];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flows/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search flows with advanced filters
         * @description Alias for GET /flows with query parameters.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of results to return */
                    limit?: components["parameters"]["Limit"];
                    /** @description Filter by job UUID */
                    job_id?: components["parameters"]["JobID"];
                    src_ip?: string;
                    dst_ip?: string;
                    protocol?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrichedFlow"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List malicious findings
         * @description Returns an aggregate view of all malicious flows and high-threat score findings.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of results to return */
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrichedFlow"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List forensics jobs
         * @description Returns a list of asynchronous processing jobs.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of jobs to return */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"][];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Persistence disabled */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Submit a forensics job
         * @description Enqueues a new PCAP file for processing and enrichment.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Path to the input PCAP/PCAPNG file */
                        input_path: string;
                        /** @description Directory to write JSON results */
                        output_path?: string;
                    };
                };
            };
            responses: {
                /** @description Job submitted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            job_id?: string;
                            /** @enum {string} */
                            status?: "pending";
                        };
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Async queue disabled */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job details
         * @description Returns the status and metadata for a specific job.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                /** @description Missing job ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Job not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Persistence disabled */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream job progress (SSE)
         * @description Returns a Server-Sent Events stream providing real-time status and progress updates for a specific job.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job UUID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream initiated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description Missing job ID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Persistence disabled */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enriched DNS events
         * @description Returns a list of DNS queries and responses with threat intel.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of results to return */
                    limit?: components["parameters"]["Limit"];
                    /** @description Filter by job UUID */
                    job_id?: components["parameters"]["JobID"];
                    /** @description Search for domain names */
                    query?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrichedDNSEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enriched TLS events
         * @description Returns a list of TLS handshakes (SNI/CipherSuite) with threat intel.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of results to return */
                    limit?: components["parameters"]["Limit"];
                    /** @description Filter by job UUID */
                    job_id?: components["parameters"]["JobID"];
                    /** @description Search for Server Name Indication */
                    sni?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrichedTLSEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/http": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enriched HTTP events
         * @description Returns a list of HTTP requests with threat intel.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of results to return */
                    limit?: components["parameters"]["Limit"];
                    /** @description Filter by job UUID */
                    job_id?: components["parameters"]["JobID"];
                    /** @description Search for HTTP hosts */
                    host?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrichedHTTPEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/icmp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List enriched ICMP events
         * @description Returns a list of ICMP messages with threat intel.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of results to return */
                    limit?: components["parameters"]["Limit"];
                    /** @description Filter by job UUID */
                    job_id?: components["parameters"]["JobID"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrichedICMPEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get forensics statistics
         * @description Returns counts of flows and protocol events currently in memory.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            flows?: number;
                            dns?: number;
                            tls?: number;
                            http?: number;
                            icmp?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/ioc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List custom IOC entries
         * @description Returns a list of manually added Indicators of Compromise.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of results to return */
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IOCEntry"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add a custom IOC entry
         * @description Dynamically adds an IP, domain, or hash to the local blocklist.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IOCEntry"];
                };
            };
            responses: {
                /** @description IOC entry added */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IOCEntry"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/ioc/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a custom IOC entry
         * @description Deletes an IOC entry by its database ID.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description IOC entry removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update pipeline configuration
         * @description Adjusts enrichment thresholds and sensitivities at runtime.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Configuration key (e.g., beacon_jitter_threshold) */
                        key: string;
                        /** @description Configuration value */
                        value: string;
                    };
                };
            };
            responses: {
                /** @description Configuration updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/capture/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a live capture
         * @description Initiates a real-time packet capture on a specified interface.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Network interface name (e.g., eth0, \Device\NPF_...) */
                        interface: string;
                        /** @description BPF filter string */
                        filter?: string;
                    };
                };
            };
            responses: {
                /** @description Capture job created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CaptureJob"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capture/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop a live capture
         * @description Gracefully terminates a running capture session.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Capture job ID */
                        id: number;
                    };
                };
            };
            responses: {
                /** @description Capture stopped */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the operational status of the API and connected services.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "up" | "degraded";
                            /** @enum {string} */
                            postgres?: "up" | "down" | "not_initialized";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Job: {
            /** Format: uuid */
            id?: string;
            input_path?: string;
            output_path?: string;
            /** @enum {string} */
            status?: "pending" | "processing" | "completed" | "failed";
            error?: string;
            packet_count?: number;
            flow_count?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        EnrichedFlow: {
            flow_id?: string;
            flow?: components["schemas"]["Flow"];
            src_threat?: components["schemas"]["ThreatContext"];
            dst_threat?: components["schemas"]["ThreatContext"];
            entropy_score?: number;
            is_beacon?: boolean;
            beacon_interval_s?: number;
            beacon_jitter?: number;
        };
        Flow: {
            flow_id?: string;
            src_ip?: string;
            src_port?: number;
            dst_ip?: string;
            dst_port?: number;
            protocol?: string;
            /** Format: date-time */
            start_time?: string;
            /** Format: date-time */
            end_time?: string;
            packet_count?: number;
            byte_count?: number;
        };
        ThreatContext: {
            indicator?: string;
            geo?: components["schemas"]["GeoInfo"];
            ioc_matches?: components["schemas"]["IOCMatch"][];
            threat_intel?: components["schemas"]["ThreatIntelResult"][];
            is_malicious?: boolean;
            threat_score?: number;
        };
        GeoInfo: {
            ip?: string;
            country_code?: string;
            country_name?: string;
            city?: string;
            latitude?: number;
            longitude?: number;
            asn?: number;
            asn_org?: string;
        };
        IOCMatch: {
            indicator?: string;
            /** @enum {string} */
            type?: "ip" | "domain" | "hash";
            source?: string;
            /** @enum {string} */
            severity?: "low" | "medium" | "high" | "critical";
            tags?: string[];
        };
        ThreatIntelResult: {
            indicator?: string;
            source?: string;
            malicious?: boolean;
            score?: number;
            tags?: string[];
            /** Format: date-time */
            last_reported_at?: string;
        };
        EnrichedDNSEvent: {
            event?: components["schemas"]["DNSEvent"];
            domain_threats?: components["schemas"]["ThreatContext"][];
        };
        DNSEvent: {
            /** Format: date-time */
            timestamp?: string;
            query?: string;
            qtype?: string;
            responses?: string[];
        };
        EnrichedTLSEvent: {
            event?: components["schemas"]["TLSEvent"];
            sni_threat?: components["schemas"]["ThreatContext"];
        };
        TLSEvent: {
            /** Format: date-time */
            timestamp?: string;
            sni?: string;
            version?: string;
            cipher?: string;
        };
        EnrichedHTTPEvent: {
            event?: components["schemas"]["HTTPEvent"];
            host_threat?: components["schemas"]["ThreatContext"];
        };
        HTTPEvent: {
            /** Format: date-time */
            timestamp?: string;
            method?: string;
            host?: string;
            path?: string;
            user_agent?: string;
        };
        EnrichedICMPEvent: {
            event?: components["schemas"]["ICMPEvent"];
            src_threat?: components["schemas"]["ThreatContext"];
            dst_threat?: components["schemas"]["ThreatContext"];
        };
        IOCEntry: {
            id?: number;
            indicator?: string;
            /** @enum {string} */
            type?: "ip" | "domain" | "hash";
            source?: string;
            /** @enum {string} */
            severity?: "low" | "medium" | "high" | "critical";
            tags?: string[];
            /** Format: date-time */
            created_at?: string;
        };
        CaptureJob: {
            id?: number;
            interface?: string;
            filter?: string;
            /** @enum {string} */
            status?: "running" | "stopped";
            /** Format: date-time */
            created_at?: string;
        };
        ICMPEvent: {
            /** Format: date-time */
            timestamp?: string;
            type?: number;
            code?: number;
            src_ip?: string;
            dst_ip?: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Maximum number of results to return */
        Limit: number;
        /** @description Filter by job UUID */
        JobID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
